### PR TITLE
Improving README file

### PR DESCRIPTION
**Pull request by erickpintor**

### CODE REVIEW

**Comment by eaceaser** [comment]
lgtm. 

1 question though: do the other drivers try to test against localhost by default? I seem to remember them wanting to hit cloud with a key provided in your environment? should we do that here?

**Comment by erickpintor** [comment]
I thinks that is true for most of the drivers besides Go and C# now. I found it handy to target localhost for local development but I can change that easily.

I'll open a ticket for this.

**Comment by marrony** [comment]
c# is hitting cloud as well

**Comment by erickpintor** [comment]
I open a new ticket for this: https://github.com/faunadb/sales-engineering/issues/398

**Comment by erickpintor** [comment]
I have a branch read for this but it is dependent on this PR. We need to merge this first.

**Pull request merged**
